/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from "./lib";
export type { lib };
export type { Claim } from "./Claim";
export type { IClaim } from "./IClaim";
