/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Claim } from "./contracts/claim/Claim";
export { Claim__factory } from './factories/contracts/claim/Claim__factory';
